dist: xenial
language: rust
rust:
    - stable
cache:
    - cargo
before_script:
    - rustup update
    - rustup component add clippy
    - rustup component add rustfmt
script:
    - cd testcrate
    - cargo test
    - cargo test --release
    - cargo test --features "static"
    - cargo test --features "libsodium"
    - cd ..
    - cargo fmt --all -- --check
    - cargo clippy --all
