dist: xenial
language: rust
rust:
    - stable
cache:
    - cargo
before_script:
    - rustup update
    - rustup component add clippy
    - rustup component add rustfmt
script:
    - cargo test --all
    - cargo test --all --release
    - cargo fmt --all -- --check
    - cargo clippy --all
